### ISSUE TITLE
Missing fields in metadata export

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#615]
**ISSUE**
Fields with values are not appearing in the metadata export.

Reference object: sq87bt605 - Sample for November 22nd Demo
Exported metadata: http://epigaea.curationexperts.com/metadata_exports/5/download
TTL: http://epigaea.curationexperts.com/concern/images/sq87bt605.ttl <-- this shows that all fields below have values that should be displayed

**ACCEPTANCE**
The following fields appear on the show view:
- [ ] Corporate name - may be related to #608 
- [ ] Genre - may be related to #608
- [ ] Personal name - - may be related to #608
- [ ] Embargo note - premis.TermOfRestriction
- [ ] End date - premis.hasEndDate
- [ ] Funder - relators.fnd
- [ ] Is part of - dc.isPartOf - see #437 
- [ ] License - dc.rights
- [ ] Primary date - dc11.date
- [ ] Resource type - dc.type
